# Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import re

# Files Loading

In [2]:
headers = ['Company','Company_Score','Reviews','Director','Director_Score','Company_Employee','Company_Revenue','Company_Sector_1','Company_URL_1','Company_Data_1','Company_Data_2','Company_Sector_2','Company_Sector_3','Null_column','Company_URL_2','Company_Data_3','Company_Data_4','Company_Sector_4','Company_URL_3','Company_Sector_5','Company_URL_4']

Companies = pd.read_excel('data_companies\companies_extraction.xlsx', names = headers)
Companies

Company  Company_Score              Reviews  \
0                           BOK Financial            3.6     469 evaluaciones   
1                             Live Nation            4.1   1,174 evaluaciones   
2                                    Amex            4.1   8,879 evaluaciones   
3                                 Staples            3.4  13,161 evaluaciones   
4                                M&T Bank            3.5   2,474 evaluaciones   
...                                   ...            ...                  ...   
20196           Petroleum Club of Midland            NaN                  NaN   
20197                    BSA Service Corp            NaN                  NaN   
20198  Florida SouthWestern State College            4.2      73 evaluaciones   
20199                     Grabba Leaf LLC            NaN                  NaN   
20200                  U.S. Waterproofing            4.6       8 evaluaciones   

               Director  Director_Score Company_Employee  \
0           Stacy Kymes            0.80              NaN   
1        Michael Rapino            0.89    más de 10 000   
2      Stephen J Squeri            0.85    más de 10 000   
3          Michael Motz            0.61    más de 10 000   
4            René Jones            0.78    más de 10 000   
...                 ...             ...              ...   
20196               NaN             NaN              NaN   
20197               NaN             NaN              NaN   
20198               NaN             NaN              NaN   
20199               NaN             NaN              NaN   
20200               NaN             NaN              NaN   

                   Company_Revenue                      Company_Sector_1  \
0      más de $10 mil millones USD                              Finanzas   
1                              NaN  Audiovisual y medios de comunicación   
2      más de $10 mil millones USD                              Finanzas   
3      más de $10 mil millones USD        Ventas al mayoreo y al menudeo   
4                              NaN                              Finanzas   
...                            ...                                   ...   
20196                          NaN                                   NaN   
20197                          NaN                                   NaN   
20198                          NaN                                   NaN   
20199                          NaN                                   NaN   
20200                          NaN                                   NaN   

                                        Company_URL_1 Company_Data_1  ...  \
0                       https://www.bokfinancial.com/            NaN  ...   
1      http://www.livenationentertainment.com/careers            NaN  ...   
2                    https://www.americanexpress.com/            NaN  ...   
3                            https://www.staples.com/            NaN  ...   
4                                https://www.mtb.com/            NaN  ...   
...                                               ...            ...  ...   
20196                                             NaN        11 a 50  ...   
20197                                             NaN            NaN  ...   
20198                                             NaN            NaN  ...   
20199                                             NaN            NaN  ...   
20200                                             NaN            NaN  ...   

      Company_Sector_2                                   Company_Sector_3  \
0                  NaN                                                NaN   
1                  NaN                                                NaN   
2                  NaN                                                NaN   
3                  NaN                                                NaN   
4                  NaN                                                NaN   
...                ...                  

# Data Cleaning

Let's navigate in the Dataset:

In [3]:
Companies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20201 entries, 0 to 20200
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Company           20200 non-null  object 
 1   Company_Score     14227 non-null  float64
 2   Reviews           14227 non-null  object 
 3   Director          4988 non-null   object 
 4   Director_Score    4090 non-null   float64
 5   Company_Employee  1601 non-null   object 
 6   Company_Revenue   635 non-null    object 
 7   Company_Sector_1  5773 non-null   object 
 8   Company_URL_1     3332 non-null   object 
 9   Company_Data_1    2959 non-null   object 
 10  Company_Data_2    5618 non-null   object 
 11  Company_Sector_2  2172 non-null   object 
 12  Company_Sector_3  3266 non-null   object 
 13  Null_column       0 non-null      float64
 14  Company_URL_2     3146 non-null   object 
 15  Company_Data_3    7022 non-null   object 
 16  Company_Data_4    3359 non-null   object

In [4]:
Companies.describe()

Company_Score  Director_Score  Null_column
count   14227.000000     4090.000000          0.0
mean        3.583117        0.721504          NaN
std         0.698159        0.121351          NaN
min         1.000000        0.060000          NaN
25%         3.200000        0.650000          NaN
50%         3.600000        0.740000          NaN
75%         4.000000        0.810000          NaN
max         5.000000        1.000000          NaN

We see some facts:

- Only three numerical columns. We can drop the Null_column, since we don't have values. Moreover, the column Reviews should be numerical also.
- Some columns repeated. That's because of the extraction from Power Automate, it wasn't extracted as clean as it could. We need to merge the repeated columns into a single ones.
- Columns "Company_Data_x", includes data of number of employees, or company revenue.

Let's work on it!

In [5]:
Companies = Companies.drop(columns=['Null_column'])
Companies = Companies.dropna(how='all')

## Reviews

We need to transform the column "Reviews" into a numerical data:

In [6]:
Companies['Reviews'] = Companies['Reviews'].fillna('0')
Companies['Reviews'] = Companies['Reviews'].replace(regex=r'\D', value='').astype(int)
Companies['Reviews'] = Companies['Reviews'].replace(0, np.nan)

Companies

Company  Company_Score  Reviews  \
0                           BOK Financial            3.6    469.0   
1                             Live Nation            4.1   1174.0   
2                                    Amex            4.1   8879.0   
3                                 Staples            3.4  13161.0   
4                                M&T Bank            3.5   2474.0   
...                                   ...            ...      ...   
20196           Petroleum Club of Midland            NaN      NaN   
20197                    BSA Service Corp            NaN      NaN   
20198  Florida SouthWestern State College            4.2     73.0   
20199                     Grabba Leaf LLC            NaN      NaN   
20200                  U.S. Waterproofing            4.6      8.0   

               Director  Director_Score Company_Employee  \
0           Stacy Kymes            0.80              NaN   
1        Michael Rapino            0.89    más de 10 000   
2      Stephen J Squeri            0.85    más de 10 000   
3          Michael Motz            0.61    más de 10 000   
4            René Jones            0.78    más de 10 000   
...                 ...             ...              ...   
20196               NaN             NaN              NaN   
20197               NaN             NaN              NaN   
20198               NaN             NaN              NaN   
20199               NaN             NaN              NaN   
20200               NaN             NaN              NaN   

                   Company_Revenue                      Company_Sector_1  \
0      más de $10 mil millones USD                              Finanzas   
1                              NaN  Audiovisual y medios de comunicación   
2      más de $10 mil millones USD                              Finanzas   
3      más de $10 mil millones USD        Ventas al mayoreo y al menudeo   
4                              NaN                              Finanzas   
...                            ...                                   ...   
20196                          NaN                                   NaN   
20197                          NaN                                   NaN   
20198                          NaN                                   NaN   
20199                          NaN                                   NaN   
20200                          NaN                                   NaN   

                                        Company_URL_1 Company_Data_1  \
0                       https://www.bokfinancial.com/            NaN   
1      http://www.livenationentertainment.com/careers            NaN   
2                    https://www.americanexpress.com/            NaN   
3                            https://www.staples.com/            NaN   
4                                https://www.mtb.com/            NaN   
...                                               ...            ...   
20196                                             NaN        11 a 50   
20197                                             NaN            NaN   
20198                                             NaN            NaN   
20199                                             NaN            NaN   
20200                                             NaN            NaN   

      Company_Data_2 Company_Sector_2  \
0                NaN              NaN   
1                NaN              NaN   
2                NaN              NaN   
3                NaN              NaN   
4                NaN              NaN   
...              ...              ...   
20196            NaN              NaN   
20197            NaN              NaN   
20198    501 a 1.000              NaN   
20199            NaN              NaN   
20200       51 a 200              NaN   

                                        Company_Sector_3  \
0                                                    NaN   
1                                                    NaN   
2                                

Nice!

## Sector

Let's try to merge the columns Sector:

In [7]:
Companies['Company_Sector_1'].head(50).values

array(['Finanzas', 'Audiovisual y medios de comunicación', 'Finanzas',
       'Ventas al mayoreo y al menudeo', 'Finanzas', 'Salud',
       'Venta al por mayor', 'Electricidad y Servicios públicos', nan,
       'Ventas al mayoreo y al menudeo',
       'Fabricación de productos electrónicos',
       'Energía, minería e infrastructura pública', 'Salud',
       'Farmacéutica y biotecnología', 'Aeroespacial y defensa',
       'Compañías de seguros', 'Ventas al mayoreo y al menudeo',
       'Telecomunicaciones', 'Banca y Servicios de crédito', 'Seguros',
       'Manufactura', 'Compañías de seguros', 'Salud',
       'Transporte y logística', 'Tiendas de alimentos y de bebidas',
       'Finanzas',
       'Servicios de construcción, reparación y mantenimiento',
       'Finanzas', 'Electricidad y Servicios públicos', 'Finanzas',
       'Sitio web de Intone Networks',
       'Audiovisual y medios de comunicación', 'Manufactura',
       'Manufactura', 'Consultoría y servicios comerciales', 'Educa

In [8]:
Companies['Company_Sector_2'].head(50).values

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, 'Soporte informático', nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan], dtype=object)

In [9]:
Companies['Company_Sector_3'].head(50).values

array([nan, nan, nan, nan, nan, nan, nan, nan, 'Educación', nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, 'Educación', nan, nan, nan, nan, nan, nan, nan, nan, nan],
      dtype=object)

In [10]:
Companies['Company_Sector_4'].values

array([nan, nan, nan, ..., nan, nan, nan], dtype=object)

In [11]:
Companies['Company_Sector_5'].values

array([nan, nan, nan, ..., 1962, 'Fabricación de productos de consumo',
       1957], dtype=object)

The values in the 2 and 3 columns looks good. However the values in column 1 looks worse. We need to set as null/empty all the values containing "Sitio web", because that isn't any sector. We need also to set as null the numeric values in columns 4 and 5, since they are not sector values:

In [12]:
Companies['Company_Sector_1'] = Companies['Company_Sector_1'].fillna('')
Companies.loc[Companies['Company_Sector_1'].str.contains('Sitio web'), 'Company_Sector_1'] = ''

In [13]:
Companies['Company_Sector_1'].head(50).values

array(['Finanzas', 'Audiovisual y medios de comunicación', 'Finanzas',
       'Ventas al mayoreo y al menudeo', 'Finanzas', 'Salud',
       'Venta al por mayor', 'Electricidad y Servicios públicos', '',
       'Ventas al mayoreo y al menudeo',
       'Fabricación de productos electrónicos',
       'Energía, minería e infrastructura pública', 'Salud',
       'Farmacéutica y biotecnología', 'Aeroespacial y defensa',
       'Compañías de seguros', 'Ventas al mayoreo y al menudeo',
       'Telecomunicaciones', 'Banca y Servicios de crédito', 'Seguros',
       'Manufactura', 'Compañías de seguros', 'Salud',
       'Transporte y logística', 'Tiendas de alimentos y de bebidas',
       'Finanzas',
       'Servicios de construcción, reparación y mantenimiento',
       'Finanzas', 'Electricidad y Servicios públicos', 'Finanzas', '',
       'Audiovisual y medios de comunicación', 'Manufactura',
       'Manufactura', 'Consultoría y servicios comerciales', 'Educación',
       'Gestión de activos e 

In [14]:
Companies.loc[Companies['Company_Sector_4'].apply(lambda x: isinstance(x, (int, float))), 'Company_Sector_4'] = None
Companies.loc[Companies['Company_Sector_5'].apply(lambda x: isinstance(x, (int, float))), 'Company_Sector_5'] = None

In [15]:
Companies['Company_Sector_4'].values

array([None, None, None, ..., None, None, None], dtype=object)

In [16]:
Companies['Company_Sector_5'].values

array([None, None, None, ..., None, 'Fabricación de productos de consumo',
       None], dtype=object)

Nice! Now let's merge the three columns:

In [17]:
Companies['Sector'] = Companies['Company_Sector_5'].fillna(Companies['Company_Sector_4']).fillna(Companies['Company_Sector_3']).fillna(Companies['Company_Sector_2']).fillna(Companies['Company_Sector_1'])
Companies['Sector'] = Companies['Sector'].replace('', np.nan)

In [18]:
Companies['Sector'].info()

<class 'pandas.core.series.Series'>
Int64Index: 20200 entries, 0 to 20200
Series name: Sector
Non-Null Count  Dtype 
--------------  ----- 
13777 non-null  object
dtypes: object(1)
memory usage: 315.6+ KB


In [19]:
Companies['Sector'].head(30)

0                                              Finanzas
1                  Audiovisual y medios de comunicación
2                                              Finanzas
3                        Ventas al mayoreo y al menudeo
4                                              Finanzas
5                                                 Salud
6                                    Venta al por mayor
7                     Electricidad y Servicios públicos
8                                             Educación
9                        Ventas al mayoreo y al menudeo
10                Fabricación de productos electrónicos
11            Energía, minería e infrastructura pública
12                                                Salud
13                         Farmacéutica y biotecnología
14                               Aeroespacial y defensa
15                                 Compañías de seguros
16                       Ventas al mayoreo y al menudeo
17                                   Telecomunic

Nice! Now would be interesting, translate this into english, and group them somehow in a few groups. We create the dictionary sectors.xlsx in order to do that:

In [20]:
sectors_df = pd.read_excel('master_data\sectors.xlsx')

sectors_df.head()

Sector_spanish      Agrupación_spanish  \
0                              Finanzas                Finanzas   
1  Audiovisual y medios de comunicación  Medios de comunicación   
2        Ventas al mayoreo y al menudeo                  Ventas   
3                                 Salud                   Salud   
4                    Venta al por mayor                  Ventas   

                                 Sector          Sector_Group  
0                               Finance               Finance  
1  Audiovisual and Media Communications  Media Communications  
2            Wholesale and Retail Sales                 Sales  
3                            Healthcare                Health  
4                       Wholesale Trade                 Sales

In [21]:
sectors = sectors_df.set_index('Sector_spanish')['Sector'].to_dict()
Companies['Sector'] = Companies['Sector'].map(sectors)

In [22]:
Companies['Sector'].info()

<class 'pandas.core.series.Series'>
Int64Index: 20200 entries, 0 to 20200
Series name: Sector
Non-Null Count  Dtype 
--------------  ----- 
13768 non-null  object
dtypes: object(1)
memory usage: 315.6+ KB


In [23]:
Companies['Sector'].head(30)

0                                            Finance
1               Audiovisual and Media Communications
2                                            Finance
3                         Wholesale and Retail Sales
4                                            Finance
5                                         Healthcare
6                                    Wholesale Trade
7                   Electricity and Public Utilities
8                                          Education
9                         Wholesale and Retail Sales
10                  Electronic Product Manufacturing
11         Energy, Mining, and Public Infrastructure
12                                        Healthcare
13                 Pharmaceuticals and Biotechnology
14                             Aerospace and Defense
15                               Insurance Companies
16                        Wholesale and Retail Sales
17                                Telecommunications
18                       Banking and Credit Se

In [24]:
sector_groups = sectors_df.set_index('Sector')['Sector_Group'].to_dict()
Companies['Sector_Group'] = Companies['Sector'].map(sector_groups)

In [25]:
Companies['Sector_Group'].head(30)

0                               Finance
1                  Media Communications
2                               Finance
3                                 Sales
4                               Finance
5                                Health
6                                 Sales
7                            Government
8                             Education
9                                 Sales
10                Product Manufacturing
11            Energy and Infrastructure
12                               Health
13    Pharmaceuticals and Biotechnology
14                           Government
15                            Insurance
16                                Sales
17               Information Technology
18                              Finance
19                            Insurance
20                Product Manufacturing
21                            Insurance
22                               Health
23         Transportation and Logistics
24                    Food and Beverage


Perfect!

## URL

We must do the same with the URL columns, merge them into a single one:

In [26]:
Companies['Company_URL_1'].head(50).values

array(['https://www.bokfinancial.com/',
       'http://www.livenationentertainment.com/careers',
       'https://www.americanexpress.com/', 'https://www.staples.com/',
       'https://www.mtb.com/', 'https://www.geisinger.org/',
       'http://www.yamaha-motor.com/', 'http://careers.abb/', nan,
       'http://www.publix.jobs/', 'https://www.intel.com/',
       'http://www.halliburton.com/', 'http://www.exactsciences.com/',
       'https://career.bayer.com/en/career',
       'http://www.leidos.com/careers/', 'https://www.bluecrossnc.com/',
       'https://corporate.dollartree.com/careers',
       'http://corporate.comcast.com/', 'https://www.axosbank.com/',
       'http://www.usablelife.com/', 'http://www.sherwin-williams.com/',
       'https://www.arbella.com/', 'https://www.ashcompanies.com/',
       'https://careers.southwestair.com/', 'http://www.unfi.com/',
       'http://www.visa.com/', 'http://www.fluor.com/',
       'https://jobs.discover.com/', 'https://www.srpnet.com/',
      

In [27]:
Companies['Company_URL_2'].head(50).values

array([nan, nan, nan, nan, nan, nan, nan, nan, 'https://www.nova.edu/',
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, 'http://www.artcenter.edu/', nan, nan,
       nan, nan, nan, nan, nan, nan, nan], dtype=object)

In [28]:
Companies['Company_URL_3'].values

array([nan, nan, nan, ..., nan, nan, nan], dtype=object)

In [29]:
Companies['Company_URL_4'].values

array([nan, nan, nan, ..., nan, nan, nan], dtype=object)

In [30]:
Companies['URL'] = Companies['Company_URL_4'].fillna(Companies['Company_URL_3']).fillna(Companies['Company_URL_2']).fillna(Companies['Company_URL_1'])
Companies['URL'] = Companies['URL'].replace('', np.nan)

In [31]:
Companies['URL'].info()

<class 'pandas.core.series.Series'>
Int64Index: 20200 entries, 0 to 20200
Series name: URL
Non-Null Count  Dtype 
--------------  ----- 
9003 non-null   object
dtypes: object(1)
memory usage: 315.6+ KB


Looks great!

## Revenue

Now let's work on the revenue columns. We need to merge the Company_Revenue and Company_Data_x columns. The challenge here is that the columns "Company_Data_1", "Company_Data_2" and "Company_Data_3" has revenue values in some cases, but in other cases has employee values. Let's create the new column "Revenue". One possible approach, is to get the values including USD or MXN in these columns:

In [32]:
Companies['Revenue'] = ''


for index, row in Companies.iterrows():

    if 'USD' in str(row['Company_Data_1']) or 'MXN' in str(row['Company_Data_1']):
        Companies.at[index, 'Revenue'] = row['Company_Data_1']
    elif 'USD' in str(row['Company_Data_2']) or 'MXN' in str(row['Company_Data_2']):
        Companies.at[index, 'Revenue'] = row['Company_Data_2']
    elif 'USD' in str(row['Company_Data_3']) or 'MXN' in str(row['Company_Data_3']):
        Companies.at[index, 'Revenue'] = row['Company_Data_3']
    elif 'USD' in str(row['Company_Data_4']) or 'MXN' in str(row['Company_Data_4']):
        Companies.at[index, 'Revenue'] = row['Company_Data_4']    
    elif 'USD' in str(row['Company_Revenue']) or 'MXN' in str(row['Company_Revenue']):
        Companies.at[index, 'Revenue'] = row['Company_Revenue']
        
Companies['Revenue'] = Companies['Revenue'].replace('', np.nan)

In [33]:
Companies['Revenue'].head(50).values

array(['más de $10 mil millones USD', '100 mil mdp a 200 mil mdp MXN',
       'más de $10 mil millones USD', 'más de $10 mil millones USD',
       '100 mil mdp a 200 mil mdp MXN', '10 mil mdp a 20 mil mdp MXN',
       '20 mil mdp a 100 mil mdp MXN', 'más de $10 mil millones USD',
       '10 mil mdp a 20 mil mdp MXN', 'más de $10 mil millones USD',
       'más de $10 mil millones USD', 'más de $10 mil millones USD',
       '2 mil mdp a 10 mil mdp MXN', 'más de $10 mil millones USD',
       'más de $10 mil millones USD', nan, 'más de $10 mil millones USD',
       'más de $10 mil millones USD', nan, nan,
       'más de $10 mil millones USD', nan, nan,
       'más de $10 mil millones USD', 'más de $10 mil millones USD',
       'más de $10 mil millones USD', 'más de $10 mil millones USD',
       'más de $10 mil millones USD', nan, 'más de $10 mil millones USD',
       '100 mdp a 500 mdp MXN', 'más de $10 mil millones USD',
       'más de $10 mil millones USD', 'más de $10 mil millones USD',

In [34]:
Companies['Revenue'].info()

<class 'pandas.core.series.Series'>
Int64Index: 20200 entries, 0 to 20200
Series name: Revenue
Non-Null Count  Dtype 
--------------  ----- 
7901 non-null   object
dtypes: object(1)
memory usage: 831.7+ KB


In [35]:
Companies['Revenue'].value_counts().head(15)

2 mil mdp a 10 mil mdp MXN       1479
20 mil mdp a 100 mil mdp MXN     1293
500 mdp a 2 mil mdp MXN          1275
100 mdp a 500 mdp MXN            1132
más de $10 mil millones USD       696
10 mil mdp a 20 mil mdp MXN       665
20 mdp a 100 mdp MXN              583
menos de $1 millón USD            423
100 mil mdp a 200 mil mdp MXN     355
Name: Revenue, dtype: int64

Nice! We see the values are weird, some in MXN and other in USD. The approach I'd like is to have here a categorical column, showing the size in revenue terms. Let's say, for example:

- Very Small
- Small
- Medium
- Big
- Very big

That's just an example. Let's create a dictionary in revenue.xlsx, and let's apply it:

In [36]:
revenue_df = pd.read_excel('master_data/revenue.xlsx')

revenue_df.head(15)

Keyword Revenue
0         menos de $1 millón USD    XXXS
1           20 mdp a 100 mdp MXN     XXS
2          100 mdp a 500 mdp MXN      XS
3        500 mdp a 2 mil mdp MXN       S
4     2 mil mdp a 10 mil mdp MXN       M
5    10 mil mdp a 20 mil mdp MXN       L
6   20 mil mdp a 100 mil mdp MXN      XL
7  100 mil mdp a 200 mil mdp MXN     XXL
8    más de $10 mil millones USD    XXXL

In [37]:
revenue_dict = revenue_df.set_index('Keyword')['Revenue'].to_dict()

def assign_revenue(row):
    for col in ['Revenue']:
        if isinstance(row[col], str):
            for keyword, revenue in revenue_dict.items():
                if keyword.lower() in row[col].lower():
                    return revenue
    return None

Companies['Revenue'] = Companies.apply(assign_revenue, axis=1)

In [38]:
revenue_counts = Companies['Revenue'].value_counts()

print(revenue_counts)

M       1479
XL      1293
S       1275
XS      1132
XXXL     696
L        665
XXS      583
XXXS     423
XXL      355
Name: Revenue, dtype: int64


In [39]:
Companies['Revenue'].info()

<class 'pandas.core.series.Series'>
Int64Index: 20200 entries, 0 to 20200
Series name: Revenue
Non-Null Count  Dtype 
--------------  ----- 
7901 non-null   object
dtypes: object(1)
memory usage: 831.7+ KB


Perfect!

## Employee

The next column is the Employee one. As we saw in Revenue column, here we have data mixed in the Company_Data_x columns, as well as we have data in Company_Employee column. The approach now is to get the values without the strings "USD" and "MXN", and containing numbers. Let's do it:

In [40]:
def filtrar_empleados(df, columnas):
    
    def filtrar_valor(valor):
        if pd.notnull(valor) and not any(keyword in str(valor) for keyword in ['USD', 'MXN']):
            return valor
        return None

    
    df['Employee'] = None

    
    for columna in columnas:
        filtro = df[columna].apply(filtrar_valor)
        df.loc[filtro.notnull(), 'Employee'] = df.loc[filtro.notnull(), columna]

    return df

Companies = filtrar_empleados(Companies, ['Company_Employee', 'Company_Data_1', 'Company_Data_2', 'Company_Data_3','Company_Data_4'])

In [41]:
employee_counts = Companies['Employee'].value_counts()

print(employee_counts)

De 1001 a 5000    2412
51 a 200          1788
más de 10 000     1663
201 a 500         1483
11 a 50           1324
501 a 1.000       1196
5.001 a 10.000     855
menos de 10        349
De 1 a 50            7
Name: Employee, dtype: int64


Nice! Now let's create a dictionary employees.xlsx and let's apply it:

In [42]:
employee_df = pd.read_excel('master_data/employees.xlsx')

employee_df.head(15)

Keyword Employees
0     menos de 10      XXXS
1       De 1 a 50       XXS
2         11 a 50        XS
3        51 a 200         S
4       201 a 500         M
5     501 a 1.000         L
6  De 1001 a 5000        XL
7  5.001 a 10.000       XXL
8   más de 10 000      XXXL

In [43]:
employee_dict = employee_df.set_index('Keyword')['Employees'].to_dict()

def assign_employee(row):
    for col in ['Employee']:
        if isinstance(row[col], str):
            for keyword, employees in employee_dict.items():
                if keyword.lower() in row[col].lower():
                    return employees
    return None

Companies['Employee'] = Companies.apply(assign_employee, axis=1)

In [44]:
employee_counts = Companies['Employee'].value_counts()

print(employee_counts)

XL      2412
S       1788
XXXL    1663
M       1483
XS      1324
L       1196
XXL      855
XXXS     349
XXS        7
Name: Employee, dtype: int64


In [45]:
Companies['Employee'].info()

<class 'pandas.core.series.Series'>
Int64Index: 20200 entries, 0 to 20200
Series name: Employee
Non-Null Count  Dtype 
--------------  ----- 
11077 non-null  object
dtypes: object(1)
memory usage: 831.7+ KB


In [46]:
Companies

Company  Company_Score  Reviews  \
0                           BOK Financial            3.6    469.0   
1                             Live Nation            4.1   1174.0   
2                                    Amex            4.1   8879.0   
3                                 Staples            3.4  13161.0   
4                                M&T Bank            3.5   2474.0   
...                                   ...            ...      ...   
20196           Petroleum Club of Midland            NaN      NaN   
20197                    BSA Service Corp            NaN      NaN   
20198  Florida SouthWestern State College            4.2     73.0   
20199                     Grabba Leaf LLC            NaN      NaN   
20200                  U.S. Waterproofing            4.6      8.0   

               Director  Director_Score Company_Employee  \
0           Stacy Kymes            0.80              NaN   
1        Michael Rapino            0.89    más de 10 000   
2      Stephen J Squeri            0.85    más de 10 000   
3          Michael Motz            0.61    más de 10 000   
4            René Jones            0.78    más de 10 000   
...                 ...             ...              ...   
20196               NaN             NaN              NaN   
20197               NaN             NaN              NaN   
20198               NaN             NaN              NaN   
20199               NaN             NaN              NaN   
20200               NaN             NaN              NaN   

                   Company_Revenue                      Company_Sector_1  \
0      más de $10 mil millones USD                              Finanzas   
1                              NaN  Audiovisual y medios de comunicación   
2      más de $10 mil millones USD                              Finanzas   
3      más de $10 mil millones USD        Ventas al mayoreo y al menudeo   
4                              NaN                              Finanzas   
...                            ...                                   ...   
20196                          NaN                                         
20197                          NaN                                         
20198                          NaN                                         
20199                          NaN                                         
20200                          NaN                                         

                                        Company_URL_1 Company_Data_1  ...  \
0                       https://www.bokfinancial.com/            NaN  ...   
1      http://www.livenationentertainment.com/careers            NaN  ...   
2                    https://www.americanexpress.com/            NaN  ...   
3                            https://www.staples.com/            NaN  ...   
4                                https://www.mtb.com/            NaN  ...   
...                                               ...            ...  ...   
20196                                             NaN        11 a 50  ...   
20197                                             NaN            NaN  ...   
20198                                             NaN            NaN  ...   
20199                                             NaN            NaN  ...   
20200                                             NaN            NaN  ...   

                      Company_Data_4     Company_Sector_4 Company_URL_3  \
0        más de $10 mil millones USD                 None           NaN   
1      100 mil mdp a 200 mil mdp MXN                 None           NaN   
2        más de $10 mil millones USD                 None           NaN   
3        más de $10 mil millones USD                 None           NaN   
4      100 mil mdp a 200 mil mdp MXN                 None           NaN   
...                              ...                  ...           ...   
20196                            NaN  Turismo y hospedaje           NaN   
20197                            NaN          

Looks great!

# Generating files

Now let's select the important columns, and generate them into a csv and xlsx file:

In [47]:
Companies_file = Companies[['Company','Sector','Sector_Group','Revenue','Employee','Company_Score','Reviews','Director','Director_Score','URL']]
Companies_file.to_excel('companies.xlsx', index=False)
Companies_file.to_csv('companies.csv', index=False, encoding="utf-16")

# THANK YOU!!